"""Full IPL player pool parsed from the uploaded IPL PLAYERS LIST.
Each tuple: (name, role, hand, country, city, base_price_Cr, grade).
Country/City exist only for the Grade D section of the source list.
"""

ALL_PLAYERS = [
    ('Virat Kohli', 'Batsman', 'Right', '', '', 3.0, 'A'),
    ('Sai Sudharsan', 'Batsman', 'Left', '', '', 3.0, 'A'),
    ('Suryakumar Yadav', 'Batsman', 'Right', '', '', 3.0, 'A'),
    ('Shubman Gill', 'Batsman', 'Right', '', '', 3.0, 'A'),
    ('Nicholas Pooran', 'Batsman', 'Left', '', '', 3.0, 'A'),
    ('Travis Head', 'Batsman', 'Left', '', '', 3.0, 'A'),
    ('Abhishek Sharma', 'Batsman', 'Left', '', '', 3.0, 'A'),
    ('Yashasvi Jaiswal', 'Batsman', 'Left', '', '', 3.0, 'A'),
    ('Phil Salt', 'Batsman', 'Right', '', '', 3.0, 'A'),
    ('Vaibhav Suryavanshi', 'Batsman', 'Left', '', '', 3.0, 'A'),
    ('Jasprit Bumrah', 'Bowler', 'Right', '', '', 3.0, 'A'),
    ('Arshdeep Singh', 'Bowler', 'Left', '', '', 3.0, 'A'),
    ('Mohammed Siraj', 'Bowler', 'Right', '', '', 3.0, 'A'),
    ('Varun Chakaravarthy', 'Bowler', 'Right', '', '', 3.0, 'A'),
    ('Harshal Patel', 'Bowler', 'Right', '', '', 3.0, 'A'),
    ('Noor Ahmad', 'Bowler', 'Left', '', '', 3.0, 'A'),
    ('Mitchell Starc', 'Bowler', 'Left', '', '', 3.0, 'A'),
    ('Trent Boult', 'Bowler', 'Left', '', '', 3.0, 'A'),
    ('Josh Hazlewood', 'Bowler', 'Right', '', '', 3.0, 'A'),
    ('Kagiso Rabada', 'Bowler', 'Right', '', '', 3.0, 'A'),
    ('Hardik Pandya', 'All Rounder', 'Right', '', '', 3.0, 'A'),
    ('Sunil Narine', 'All Rounder', 'Left', '', '', 3.0, 'A'),
    ('Andre Russell', 'All Rounder', 'Right', '', '', 3.0, 'A'),
    ('Ravindra Jadeja', 'All Rounder', 'Left', '', '', 3.0, 'A'),
    ('Axar Patel', 'All Rounder', 'Left', '', '', 3.0, 'A'),
    ('Krunal Pandya', 'All Rounder', 'Left', '', '', 3.0, 'A'),
    ('Nitish Kumar Reddy', 'All Rounder', 'Right', '', '', 3.0, 'A'),
    ('Marcus Stoinis', 'All Rounder', 'Right', '', '', 3.0, 'A'),
    ('Washington Sundar', 'All Rounder', 'Left', '', '', 3.0, 'A'),
    ('Cameron Green', 'All Rounder', 'Right', '', '', 3.0, 'A'),
    ('Sanju Samson', 'Wicketkeeper', 'Right', '', '', 3.0, 'A'),
    ('Rishabh Pant', 'Wicketkeeper', 'Left', '', '', 3.0, 'A'),
    ('KL Rahul', 'Wicketkeeper', 'Right', '', '', 3.0, 'A'),
    ('Ishan Kishan', 'Wicketkeeper', 'Left', '', '', 3.0, 'A'),
    ('Jitesh Sharma', 'Wicketkeeper', 'Right', '', '', 3.0, 'A'),
    ('Heinrich Klaasen', 'Wicketkeeper', 'Right', '', '', 3.0, 'A'),
    ('Ruturaj Gaikwad', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Devdutt Padikkal', 'Batsman', 'Left', '', '', 2.0, 'B'),
    ('Tilak Varma', 'Batsman', 'Left', '', '', 2.0, 'B'),
    ('Nehal Wadhera', 'Batsman', 'Left', '', '', 2.0, 'B'),
    ('Rinku Singh', 'Batsman', 'Left', '', '', 2.0, 'B'),
    ('Ajinkya Rahane', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Rahul Tripathi', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Angkrish Raghuvanshi', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Ashutosh Sharma', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Priyansh Arya', 'Batsman', 'Left', '', '', 2.0, 'B'),
    ('Karun Nair', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Sameer Rizvi', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Sherfane Rutherford', 'Batsman', 'Left', '', '', 2.0, 'B'),
    ('Dewald Brevis', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Tim David', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Faf du Plessis', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('David Miller', 'Batsman', 'Left', '', '', 2.0, 'B'),
    ('Rovman Powell', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Shimron Hetmyer', 'Batsman', 'Left', '', '', 2.0, 'B'),
    ('Harry Brook', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Aiden Markram', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Rahul Tewatia', 'Batsman', 'Left', '', '', 2.0, 'B'),
    ('Ramandeep Singh', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Ayush Badoni', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Rohit Sharma', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Abdul Samad', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Shahrukh Khan', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Manish Pandey', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Sai Kishore', 'Batsman', 'Left', '', '', 2.0, 'B'),
    ('Rajat Patidar', 'Batsman', 'Right', '', '', 2.0, 'B'),
    ('Bhuvneshwar Kumar', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Avesh Khan', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Mukesh Kumar', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Khaleel Ahmed', 'Bowler', 'Left', '', '', 2.0, 'B'),
    ('Deepak Chahar', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Yash Dayal', 'Bowler', 'Left', '', '', 2.0, 'B'),
    ('Akash Deep', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Mohsin Khan', 'Bowler', 'Left', '', '', 2.0, 'B'),
    ('Simarjeet Singh', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Yash Thakur', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Mayank Yadav', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Nandre Burger', 'Bowler', 'Left', '', '', 2.0, 'B'),
    ('Gerald Coetzee', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Prasidh Krishna', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('T. Natarajan', 'Bowler', 'Left', '', '', 2.0, 'B'),
    ('Kuldeep Yadav', 'Bowler', 'Left', '', '', 2.0, 'B'),
    ('Lockie Ferguson', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Matheesha Pathirana', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Spencer Johnson', 'Bowler', 'Left', '', '', 2.0, 'B'),
    ('Richard Gleeson', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Yuzvendra Chahal', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Ravi Bishnoi', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('R. Sai Kishore', 'Bowler', 'Left', '', '', 2.0, 'B'),
    ('Maheesh Theekshana', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Rahul Chahar', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Suyash Sharma', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Karn Sharma', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('M. Siddharth', 'Bowler', 'Left', '', '', 2.0, 'B'),
    ('Shamar Joseph', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Anrich Nortje', 'Bowler', 'Right', '', '', 2.0, 'B'),
    ('Shivam Dube', 'All Rounder', 'Left', '', '', 2.0, 'B'),
    ('Shahbaz Ahmed', 'All Rounder', 'Left', '', '', 2.0, 'B'),
    ('Vijay Shankar', 'All Rounder', 'Right', '', '', 2.0, 'B'),
    ('Deepak Hooda', 'All Rounder', 'Right', '', '', 2.0, 'B'),
    ('Liam Livingstone', 'All Rounder', 'Right', '', '', 2.0, 'B'),
    ('Glenn Maxwell', 'All Rounder', 'Right', '', '', 2.0, 'B'),
    ('Romario Shepherd', 'All Rounder', 'Right', '', '', 2.0, 'B'),
    ('Marco Jansen', 'All Rounder', 'Left', '', '', 2.0, 'B'),
    ('Moeen Ali', 'All Rounder', 'Left', '', '', 2.0, 'B'),
    ('Will Jacks', 'All Rounder', 'Right', '', '', 2.0, 'B'),
    ('Michael Bracewell', 'All Rounder', 'Right', '', '', 2.0, 'B'),
    ('Azmatullah Omarzai', 'All Rounder', 'Right', '', '', 2.0, 'B'),
    ('Swapnil Singh', 'All Rounder', 'Left', '', '', 2.0, 'B'),
    ('MS Dhoni', 'Wicketkeeper', 'Right', '', '', 2.0, 'B'),
    ('Dhruv Jurel', 'Wicketkeeper', 'Right', '', '', 2.0, 'B'),
    ('Ryan Rickelton', 'Wicketkeeper', 'Left', '', '', 2.0, 'B'),
    ('Quinton de Kock', 'Wicketkeeper', 'Left', '', '', 2.0, 'B'),
    ('Rahmanullah Gurbaz', 'Wicketkeeper', 'Right', '', '', 2.0, 'B'),
    ('Devon Conway', 'Wicketkeeper', 'Left', '', '', 2.0, 'B'),
    ('Josh Inglis', 'Wicketkeeper', 'Right', '', '', 2.0, 'B'),
    ('Anuj Rawat', 'Wicketkeeper', 'Left', '', '', 2.0, 'B'),
    ('Vishnu Vinod', 'Wicketkeeper', 'Right', '', '', 2.0, 'B'),
    ('Robin Minz', 'Wicketkeeper', 'Left', '', '', 2.0, 'B'),
    ('Nitish Rana', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Sarfaraz Khan', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Mandeep Singh', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Harpreet Bhatia', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Shaik Rasheed', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Harnoor Singh', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Musheer Khan', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Swastik Chikara', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Yash Dhull', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Vishnu Solanki', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Rohan Kunnummal', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Ricky Bhui', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Virat Singh', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Suyash Prabhudessai', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Smaran Ravichandran', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Priyam Garg', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Harnoor Pannu', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Karan Sharma', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Rohan Patil', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Shubham Dubey', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Pukhraj Mann', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Ansh Gosai', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Saurabh Chauhan', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Arshin Kulkarni', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Arpit Guleria', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Ravichandran Smaran', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Himmat Singh', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Utkarsh Singh', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Sandeep Warrier', 'Batsman', 'Right', '', '', 1.0, 'C'),
    ('Shoun Roger', 'Batsman', 'Left', '', '', 1.0, 'C'),
    ('Navdeep Saini', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Umesh Yadav', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Ishant Sharma', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Sandeep Sharma', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Chetan Sakariya', 'Bowler', 'Left', '', '', 1.0, 'C'),
    ('Kartik Tyagi', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Vidwath Kaverappa', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Rasikh Dar Salam', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Vaibhav Arora', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Arjun Tendulkar', 'Bowler', 'Left', '', '', 1.0, 'C'),
    ('Xavier Bartlett', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Nathan Ellis', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Mustafizur Rahman', 'Bowler', 'Left', '', '', 1.0, 'C'),
    ('Alzarri Joseph', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Fazalhaq Farooqi', 'Bowler', 'Left', '', '', 1.0, 'C'),
    ('Naveen-ul-Haq', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Reece Topley', 'Bowler', 'Left', '', '', 1.0, 'C'),
    ('Blessing Muzarabani', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Adam Zampa', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Tabraiz Shamsi', 'Bowler', 'Left', '', '', 1.0, 'C'),
    ('Mujeeb Ur Rahman', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Adil Rashid', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Kumar Kartikeya', 'Bowler', 'Left', '', '', 1.0, 'C'),
    ('Shreyas Gopal', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Digvesh Rathi', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Yuvraj Choudhary', 'Bowler', 'Left', '', '', 1.0, 'C'),
    ('Zeeshan Ansari', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Pravin Dubey', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Murugan Ashwin', 'Bowler', 'Right', '', '', 1.0, 'C'),
    ('Akash Singh', 'Bowler', 'Left', '', '', 1.0, 'C'),
    ('Ravichandran Ashwin', 'All Rounder', 'Right', '', '', 1.0, 'C'),
    ('Mitchell Santner', 'All Rounder', 'Left', '', '', 1.0, 'C'),
    ('Krishnappa Gowtham', 'All Rounder', 'Right', '', '', 1.0, 'C'),
    ('Sikandar Raza', 'All Rounder', 'Right', 'Zimbabwe', '', 1.0, 'C'),
    ('Shakib Al Hasan', 'All Rounder', 'Left', 'Bangladesh', '', 1.0, 'C'),
    ('Daryl Mitchell', 'All Rounder', 'Right', '', '', 1.0, 'C'),
    ('Roston Chase', 'All Rounder', 'Right', 'West Indies', '', 1.0, 'C'),
    ('Odean Smith', 'All Rounder', 'Right', '', '', 1.0, 'C'),
    ('Chamika Karunaratne', 'All Rounder', 'Right', 'Sri Lanka', '', 1.0, 'C'),
    ('Daniel Sams', 'All Rounder', 'Left', '', '', 1.0, 'C'),
    ('Matthew Short', 'All Rounder', 'Right', '', '', 1.0, 'C'),
    ('Wiaan Mulder', 'All Rounder', 'Right', 'South Africa', '', 1.0, 'C'),
    ('Kyle Mayers', 'All Rounder', 'Left', '', '', 1.0, 'C'),
    ('Dasun Shanaka', 'All Rounder', 'Right', 'Sri Lanka', '', 1.0, 'C'),
    ('Jason Holder', 'All Rounder', 'Right', 'West Indies', '', 1.0, 'C'),
    ('Jimmy Neesham', 'All Rounder', 'Left', 'New Zealand', '', 1.0, 'C'),
    ('Chris Green', 'All Rounder', 'Right', '', '', 1.0, 'C'),
    ('Nishant Sindhu', 'All Rounder', 'Left', '', '', 1.0, 'C'),
    ('Shams Mulani', 'All Rounder', 'Left', '', '', 1.0, 'C'),
    ('Raj Bawa', 'All Rounder', 'Left', '', '', 1.0, 'C'),
    ('Sanvir Singh', 'All Rounder', 'Right', '', '', 1.0, 'C'),
    ('Manvanth Kumar', 'All Rounder', 'Right', '', '', 1.0, 'C'),
    ('Bipin Saurabh', 'All Rounder', 'Left', '', '', 1.0, 'C'),
    ('Saurabh Kumar', 'All Rounder', 'Left', '', '', 1.0, 'C'),
    ('Harsh Dubey', 'All Rounder', 'Left', '', '', 1.0, 'C'),
    ('Anukul Roy', 'All Rounder', 'Left', '', '', 1.0, 'C'),
    ('Tanush Kotian', 'All Rounder', 'Right', '', '', 1.0, 'C'),
    ('KS Bharat', 'Wicketkeeper', 'Right', '', '', 1.0, 'C'),
    ('Luvnith Sisodia', 'Wicketkeeper', 'Left', '', '', 1.0, 'C'),
    ('Kumar Kushagra', 'Wicketkeeper', 'Right', '', '', 1.0, 'C'),
    ('Urvil Patel', 'Wicketkeeper', 'Right', '', '', 1.0, 'C'),
    ('Joe Root', 'Batsman', '', 'England', '', 0.5, 'D'),
    ('Dawid Malan', 'Batsman', '', 'England', '', 0.5, 'D'),
    ('Tom Bruce', 'Batsman', '', 'New Zealand', '', 0.5, 'D'),
    ('Ben McKinney', 'Batsman', '', 'England', '', 0.5, 'D'),
    ('Sam Konstas', 'Batsman', '', 'Australia', '', 0.5, 'D'),
    ('Hugh Weibgen', 'Batsman', '', 'Australia', '', 0.5, 'D'),
    ('Harry Dixon', 'Batsman', '', 'Australia', '', 0.5, 'D'),
    ('Lhuan-dré Pretorius', 'Batsman', '', 'South Africa', '', 0.5, 'D'),
    ('Ollie Peake', 'Batsman', '', 'Australia', '', 0.5, 'D'),
    ('Hamza Shaikh', 'Batsman', '', 'England', '', 0.5, 'D'),
    ('Shaheen Shah Afridi', 'Bowler', '', 'Pakistan', '', 0.5, 'D'),
    ('Haris Rauf', 'Bowler', '', 'Pakistan', '', 0.5, 'D'),
    ('Naseem Shah', 'Bowler', '', 'Pakistan', '', 0.5, 'D'),
    ('Hasan Ali', 'Bowler', '', 'Pakistan', '', 0.5, 'D'),
    ('Mohammad Wasim Jr.', 'Bowler', '', 'Pakistan', '', 0.5, 'D'),
    ('Abrar Ahmed', 'Bowler', '', 'Pakistan', '', 0.5, 'D'),
    ('Usama Mir', 'Bowler', '', 'Pakistan', '', 0.5, 'D'),
    ('Keshav Maharaj', 'Bowler', '', 'South Africa', '', 0.5, 'D'),
    ('Matthew Potts', 'Bowler', '', 'England', '', 0.5, 'D'),
    ('George Scrimshaw', 'Bowler', '', 'England', '', 0.5, 'D'),
    ('Tom Latham', 'Wicketkeeper', '', 'New Zealand', '', 0.5, 'D'),
    ('Tim Seifert', 'Wicketkeeper', '', 'New Zealand', '', 0.5, 'D'),
    ('Amit Shukla', 'All Rounder', '', 'India', 'Services', 0.5, 'D'),
    ('Devang Karamta', 'Bowler', '', 'India', 'Gujarat', 0.5, 'D'),
    ('Yuvraj Singh Dodiya', 'All Rounder', '', 'India', 'Saurashtra', 0.5, 'D'),
    ('Parth Rekhade', 'All Rounder', '', 'India', 'Vidarbha', 0.5, 'D'),
    ('Siddharth Desai', 'Bowler', '', 'India', 'Gujarat', 0.5, 'D'),
    ('Dharmendrasinh Jadeja', 'Bowler', '', 'India', 'Saurashtra', 0.5, 'D'),
    ('Karan Patel', 'All Rounder', '', 'India', 'Gujarat', 0.5, 'D'),
    ('Jaymeet Patel', 'Batsman', '', 'India', 'Gujarat', 0.5, 'D'),
    ('Het Patel', 'Batsman', '', 'India', 'Gujarat', 0.5, 'D'),
    ('Urvil Panchal', 'Batsman', '', 'India', 'Gujarat', 0.5, 'D'),
    ('Akshit Goel', 'Batsman', '', 'India', 'Haryana', 0.5, 'D'),
    ('Nishchal Dahiya', 'Batsman', '', 'India', 'Haryana', 0.5, 'D'),
    ('Dinesh Bana', 'Wicketkeeper', '', 'India', 'Haryana', 0.5, 'D'),
    ('Ankit Kumar', 'Batsman', '', 'India', 'Haryana', 0.5, 'D'),
    ('Kunal Singh', 'Batsman', '', 'India', 'Chandigarh', 0.5, 'D'),
    ('Arslan Khan', 'Batsman', '', 'India', 'Chandigarh', 0.5, 'D'),
    ('Paras Dogra', 'Batsman', '', 'India', 'Puducherry', 0.5, 'D'),
    ('Arun Karthik', 'Batsman', '', 'India', 'Tamil Nadu', 0.5, 'D'),
    ('Baba Aparajith', 'All Rounder', '', 'India', 'Tamil Nadu', 0.5, 'D'),
    ('Baba Indrajith', 'Batsman', '', 'India', 'Tamil Nadu', 0.5, 'D'),
    ('C. Andre Siddarth', 'Batsman', '', 'India', 'Tamil Nadu', 0.5, 'D'),
    ('Pradosh Ranjan Paul', 'Batsman', '', 'India', 'Tamil Nadu', 0.5, 'D'),
    ('K. Easwaran', 'Batsman', '', 'India', 'Tamil Nadu', 0.5, 'D'),
    ('Nidhish Rajagopal', 'Batsman', '', 'India', 'Tamil Nadu', 0.5, 'D'),
    ('R. Sonu Yadav', 'All Rounder', '', 'India', 'Tamil Nadu', 0.5, 'D'),
    ('Sachin Baby', 'Batsman', '', 'India', 'Kerala', 0.5, 'D'),
    ('Akshay Chandran', 'All Rounder', '', 'India', 'Kerala', 0.5, 'D'),
    ('Jalaj Saxena', 'All Rounder', '', 'India', 'Kerala', 0.5, 'D'),
    ('Krishna Prasad', 'Batsman', '', 'India', 'Kerala', 0.5, 'D'),
    ('Akhil Scaria', 'All Rounder', '', 'India', 'Kerala', 0.5, 'D'),
    ('Devdhar Kalal', 'Batsman', '', 'India', 'Goa', 0.5, 'D'),
    ('Snehal Kauthankar', 'Batsman', '', 'India', 'Goa', 0.5, 'D'),
    ('Darshan Misal', 'All Rounder', '', 'India', 'Goa', 0.5, 'D'),
    ('Sumit Kumar', 'All Rounder', '', 'India', 'Haryana', 0.5, 'D'),
    ('Mayank Dagar', 'All Rounder', '', 'India', 'Himachal Pradesh', 0.5, 'D'),
    ('Nikhil Gangta', 'Batsman', '', 'India', 'Himachal Pradesh', 0.5, 'D'),
    ('Ekant Sen', 'Batsman', '', 'India', 'Madhya Pradesh', 0.5, 'D'),
    ('Shubhranshu Senapati', 'Batsman', '', 'India', 'Odisha', 0.5, 'D'),
    ('Govinda Poddar', 'All Rounder', '', 'India', 'Odisha', 0.5, 'D'),
    ('Subhranshu Mishra', 'Batsman', '', 'India', 'Odisha', 0.5, 'D'),
    ('Avneesh Sudha', 'Batsman', '', 'India', 'Uttarakhand', 0.5, 'D'),
    ('Kunal Chandela', 'Batsman', '', 'India', 'Uttarakhand', 0.5, 'D'),
    ('Aryan Borah', 'Batsman', '', 'India', 'Assam', 0.5, 'D'),
    ('Denish Das', 'Batsman', '', 'India', 'Assam', 0.5, 'D'),
    ('Rahul Hazarika', 'Batsman', '', 'India', 'Assam', 0.5, 'D'),
    ('Sudip Chatterjee', 'Batsman', '', 'India', 'Bengal', 0.5, 'D'),
    ('Sudip Kumar Gharami', 'Batsman', '', 'India', 'Bengal', 0.5, 'D'),
    ('Abishek Porel', 'Wicketkeeper', '', 'India', 'Bengal', 0.5, 'D'),
]
